version: "3.9"

services:
  risb:
    image: risb:3.2.x
    container_name: risb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TRIQSTAG=3.2.0
    volumes:
      - "./:/home/build/src/risb:ro"
    stdin_open: true # docker run -i
    tty: true        # docker run -t