services:
  jekyll:
    image: risb-docs
    container_name: risb-docs
    build:
      context: ../docs/
      dockerfile: ../docker/Dockerfile.docs
    ports:
      - 4000:4000
    volumes:
      - "../docs/:/usr/src/app"
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t